/*
 * Virtual Machine Management API of the Ghaf platform - OpenAPI
 *
 * OpenAPI specification for virtual machine management on Ghaf platform
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: nikita.bazulin@unikie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorModel {
    #[serde(rename = "code", deserialize_with = "Option::deserialize")]
    pub code: Option<serde_json::Value>,
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<serde_json::Value>,
}

impl ErrorModel {
    pub fn new(code: Option<serde_json::Value>, message: Option<serde_json::Value>) -> ErrorModel {
        ErrorModel {
            code,
            message,
        }
    }
}


