/*
 * Virtual Machine Management API of the Ghaf platform - OpenAPI
 *
 * OpenAPI specification for virtual machine management on Ghaf platform
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: nikita.bazulin@unikie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualMachinePerformance {
    /// CPU load %
    #[serde(rename = "cpuUsage", deserialize_with = "Option::deserialize")]
    pub cpu_usage: Option<serde_json::Value>,
    /// Memory usage in MB
    #[serde(rename = "memoryUsage", deserialize_with = "Option::deserialize")]
    pub memory_usage: Option<serde_json::Value>,
    /// Disk IO in KB/s
    #[serde(rename = "diskIo", deserialize_with = "Option::deserialize")]
    pub disk_io: Option<serde_json::Value>,
    /// Network IO in KB/s
    #[serde(rename = "networkIo", deserialize_with = "Option::deserialize")]
    pub network_io: Option<serde_json::Value>,
}

impl VirtualMachinePerformance {
    pub fn new(cpu_usage: Option<serde_json::Value>, memory_usage: Option<serde_json::Value>, disk_io: Option<serde_json::Value>, network_io: Option<serde_json::Value>) -> VirtualMachinePerformance {
        VirtualMachinePerformance {
            cpu_usage,
            memory_usage,
            disk_io,
            network_io,
        }
    }
}


