/*
 * Virtual Machine Management API of the Ghaf platform - OpenAPI
 *
 * OpenAPI specification for virtual machine management on Ghaf platform
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: nikita.bazulin@unikie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualMachineMemory {
    /// Total host memory in MB
    #[serde(rename = "totalHost", deserialize_with = "Option::deserialize")]
    pub total_host: Option<serde_json::Value>,
    /// Currently allocated memory by VM in MB
    #[serde(rename = "currentAllocation", deserialize_with = "Option::deserialize")]
    pub current_allocation: Option<serde_json::Value>,
    /// Maximum possible allocated memory by VM in MB
    #[serde(rename = "maximumAllocation", deserialize_with = "Option::deserialize")]
    pub maximum_allocation: Option<serde_json::Value>,
}

impl VirtualMachineMemory {
    pub fn new(total_host: Option<serde_json::Value>, current_allocation: Option<serde_json::Value>, maximum_allocation: Option<serde_json::Value>) -> VirtualMachineMemory {
        VirtualMachineMemory {
            total_host,
            current_allocation,
            maximum_allocation,
        }
    }
}


