/*
 * Virtual Machine Management API of the Ghaf platform - OpenAPI
 *
 * OpenAPI specification for virtual machine management on Ghaf platform
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: nikita.bazulin@unikie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualMachineCpu {
    #[serde(rename = "model", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<serde_json::Value>>,
    #[serde(rename = "logicalCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logical_count: Option<Option<serde_json::Value>>,
    #[serde(rename = "sockets", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sockets: Option<Option<serde_json::Value>>,
    #[serde(rename = "cores", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cores: Option<Option<serde_json::Value>>,
    #[serde(rename = "threads", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub threads: Option<Option<serde_json::Value>>,
}

impl VirtualMachineCpu {
    pub fn new() -> VirtualMachineCpu {
        VirtualMachineCpu {
            model: None,
            logical_count: None,
            sockets: None,
            cores: None,
            threads: None,
        }
    }
}


