/*
 * Virtual Machine Management API of the Ghaf platform - OpenAPI
 *
 * OpenAPI specification for virtual machine management on Ghaf platform
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: nikita.bazulin@unikie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualMachineOs {
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<serde_json::Value>,
    #[serde(rename = "version", deserialize_with = "Option::deserialize")]
    pub version: Option<serde_json::Value>,
}

impl VirtualMachineOs {
    pub fn new(name: Option<serde_json::Value>, version: Option<serde_json::Value>) -> VirtualMachineOs {
        VirtualMachineOs {
            name,
            version,
        }
    }
}


