/*
 * Virtual Machine Management API of the Ghaf platform - OpenAPI
 *
 * OpenAPI specification for virtual machine management on Ghaf platform
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: nikita.bazulin@unikie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualMachineDevices {
    #[serde(rename = "list", deserialize_with = "Option::deserialize")]
    pub list: Option<serde_json::Value>,
}

impl VirtualMachineDevices {
    pub fn new(list: Option<serde_json::Value>) -> VirtualMachineDevices {
        VirtualMachineDevices {
            list,
        }
    }
}


